server:
  port: 8080

#开发配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.154.137:3306/godzilla?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/easondb?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    url: jdbc:mysql://172.31.234.106:3306/drug2?useUnicode=true&characterEncoding=UTF-8
#    username: cdss
#    password: Cdss!2018
    resources:
  static-locations: classpath:/static/,classpath:/static/,classpath:/resources/,classpath:/META-INF/resources/


config:
  jiraPath: http://jira.iflytek.com
  userName: junwang33
  pswd: WJ--lyp82nlf


security:
  basic:
    enabled: false
  headers:
    frame: false
