server:
  port: 8080

#开发配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://140.143.230.126:3306/godzilla?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root